//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO_Blog
    {
        public int idBlog { get; set; }
        public string nvTitulo { get; set; }
        public string nvTexto { get; set; }
        public Nullable<System.DateTime> dtFechaSubida { get; set; }
        public Nullable<int> Activo { get; set; }
        public string imgBlog { get; set; }
    }
}
