//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO_Blog
    {
        public int IdBlog { get; set; }
        public string nvTitulo { get; set; }
        public string nvTexto { get; set; }
        public byte[] imgBlog { get; set; }
        public Nullable<System.DateTime> dtFechaSubida { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
