//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO_Costo
    {
        public Nullable<decimal> CostoLugar { get; set; }
        public int IdDestino { get; set; }
        public Nullable<int> IdSalida { get; set; }
        public Nullable<int> IdHabitacion { get; set; }
        public Nullable<int> IdViaje { get; set; }
        public string TipoPersona { get; set; }
    
        public virtual TO_Destino TO_Destino { get; set; }
        public virtual TO_Habitaciones TO_Habitaciones { get; set; }
        public virtual TO_Salida TO_Salida { get; set; }
        public virtual TO_Viajes TO_Viajes { get; set; }
    }
}
