//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO_Costo
    {
        public Nullable<decimal> CostoLugar { get; set; }
        public int IdDestino { get; set; }
        public Nullable<int> IdSalida { get; set; }
        public Nullable<int> IdHabitacion { get; set; }
        public string TipoPersona { get; set; }
    
        public virtual TO_Destino TO_Destino { get; set; }
        public virtual TO_Habitaciones TO_Habitaciones { get; set; }
        public virtual TO_Salida TO_Salida { get; set; }
    }
}
