//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO_DetalleDestinos
    {
        public int Id_Detalle { get; set; }
        public int Id_Destino { get; set; }
        public string nvRutaArchivo { get; set; }
        public string nvDescripcion { get; set; }
        public Nullable<System.DateTime> dtFechaAlta { get; set; }
        public Nullable<bool> bActivo { get; set; }
    
        public virtual TO_Destino TO_Destino { get; set; }
    }
}
