//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO_DetalleDestinos
    {
        public int Id_Detalle { get; set; }
        public int Id_Destino { get; set; }
        public string nvRutaArchivo { get; set; }
        public string nvDescripcion { get; set; }
        public Nullable<System.DateTime> dtFechaAlta { get; set; }
        public Nullable<bool> bActivo { get; set; }
    
        public virtual TO_Destino TO_Destino { get; set; }
    }
}
