//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO_EncuestaResp
    {
        public int IdResEnc { get; set; }
        public string NombrePersona { get; set; }
        public int IdPregunta { get; set; }
        public int IdDestino { get; set; }
        public string nvRespuesta { get; set; }
        public Nullable<System.DateTime> dtFechaEncuesta { get; set; }
        public Nullable<System.DateTime> dtFechaViaje { get; set; }
    
        public virtual TO_Destino TO_Destino { get; set; }
        public virtual TO_Encuesta TO_Encuesta { get; set; }
    }
}
