//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO_Experiencias
    {
        public int IdExp { get; set; }
        public string Nombre { get; set; }
        public string Testimonio { get; set; }
        public int IdDestino { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public Nullable<decimal> Calificacion { get; set; }
        public byte[] ImgDestino { get; set; }
    
        public virtual TO_Destino TO_Destino { get; set; }
    }
}
