//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO_Viajes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TO_Viajes()
        {
            this.TO_Viajeros = new HashSet<TO_Viajeros>();
            this.TO_Costo = new HashSet<TO_Costo>();
        }
    
        public int IdViaje { get; set; }
        public int Id_Destino { get; set; }
        public int Id_Salida { get; set; }
        public Nullable<System.DateTime> dtFechaSalida { get; set; }
        public Nullable<int> IdTransporte { get; set; }
        public Nullable<System.DateTime> dtFechaLleg { get; set; }
        public Nullable<int> iRelacion { get; set; }
    
        public virtual TO_Destino TO_Destino { get; set; }
        public virtual TO_Salida TO_Salida { get; set; }
        public virtual TO_Transporte TO_Transporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TO_Viajeros> TO_Viajeros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TO_Costo> TO_Costo { get; set; }
    }
}
