//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO_Viajeros
    {
        public int Folio { get; set; }
        public Nullable<int> IdViaje { get; set; }
        public string IdUsuario { get; set; }
        public string NombreAsistente { get; set; }
        public string ApAsistente { get; set; }
        public string Correo { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<int> Asiento { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
        public Nullable<decimal> Pagado { get; set; }
        public Nullable<decimal> Deuda { get; set; }
        public byte[] Pago { get; set; }
        public Nullable<bool> Confirmado { get; set; }
    
        public virtual TO_Usuario TO_Usuario { get; set; }
        public virtual TO_Viajes TO_Viajes { get; set; }
    }
}
