//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TO_Viajeros
    {
        public int Folio { get; set; }
        public Nullable<int> IdViaje { get; set; }
        public string IdUsuario { get; set; }
        public string NombreAsistente { get; set; }
        public string ApAsistente { get; set; }
        public string Correo { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<int> Asiento { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
        public Nullable<decimal> Pagado { get; set; }
        public Nullable<decimal> Deuda { get; set; }
        public byte[] Pago { get; set; }
    
        public virtual TO_Usuario TO_Usuario { get; set; }
        public virtual TO_Viajes TO_Viajes { get; set; }
    }
}
