//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOA_Usuario
    {
        public string nvUsuario { get; set; }
        public string nvContraseña { get; set; }
        public string nvNombre { get; set; }
        public string nvApPat { get; set; }
        public string nvApMat { get; set; }
        public string nvCorreo { get; set; }
        public Nullable<System.DateTime> dtFecNac { get; set; }
        public Nullable<System.DateTime> dtFecReg { get; set; }
        public Nullable<System.DateTime> dtFecAct { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
