//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOA_Usuario
    {
        public string nvUsuario { get; set; }
        public string nvContraseña { get; set; }
        public string nvNombre { get; set; }
        public string nvApPat { get; set; }
        public string nvApMat { get; set; }
        public string nvCorreo { get; set; }
        public Nullable<System.DateTime> dtFecNac { get; set; }
        public Nullable<System.DateTime> dtFecReg { get; set; }
        public Nullable<System.DateTime> dtFecAct { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
