//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TravelOKEntitiesQA : DbContext
    {
        public TravelOKEntitiesQA()
            : base("name=TravelOKEntitiesQA")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TO_Destino> TO_Destino { get; set; }
        public virtual DbSet<TO_Experiencias> TO_Experiencias { get; set; }
        public virtual DbSet<TO_Salida> TO_Salida { get; set; }
        public virtual DbSet<TO_Usuario> TO_Usuario { get; set; }
        public virtual DbSet<TO_Costo> TO_Costo { get; set; }
        public virtual DbSet<TO_Blog> TO_Blog { get; set; }
        public virtual DbSet<TOA_Usuario> TOA_Usuario { get; set; }
        public virtual DbSet<TO_DetalleDestinos> TO_DetalleDestinos { get; set; }
    
        public virtual int spInsertaComunidad(string nombre, string testimonio, Nullable<int> idViaje, Nullable<decimal> calificacion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var testimonioParameter = testimonio != null ?
                new ObjectParameter("Testimonio", testimonio) :
                new ObjectParameter("Testimonio", typeof(string));
    
            var idViajeParameter = idViaje.HasValue ?
                new ObjectParameter("IdViaje", idViaje) :
                new ObjectParameter("IdViaje", typeof(int));
    
            var calificacionParameter = calificacion.HasValue ?
                new ObjectParameter("Calificacion", calificacion) :
                new ObjectParameter("Calificacion", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertaComunidad", nombreParameter, testimonioParameter, idViajeParameter, calificacionParameter);
        }
    
        public virtual ObjectResult<spObtieneComunidad_Result> spObtieneComunidad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spObtieneComunidad_Result>("spObtieneComunidad");
        }
    
        public virtual int spdEliminaSalida(string nvSalida)
        {
            var nvSalidaParameter = nvSalida != null ?
                new ObjectParameter("nvSalida", nvSalida) :
                new ObjectParameter("nvSalida", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spdEliminaSalida", nvSalidaParameter);
        }
    
        public virtual int spdEliminaSalidaId(Nullable<int> idSalida)
        {
            var idSalidaParameter = idSalida.HasValue ?
                new ObjectParameter("idSalida", idSalida) :
                new ObjectParameter("idSalida", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spdEliminaSalidaId", idSalidaParameter);
        }
    
        public virtual int spiAgregaImDestinosC(Nullable<int> id_Destino, string nvRutaArchivo, string nvDescripcion)
        {
            var id_DestinoParameter = id_Destino.HasValue ?
                new ObjectParameter("Id_Destino", id_Destino) :
                new ObjectParameter("Id_Destino", typeof(int));
    
            var nvRutaArchivoParameter = nvRutaArchivo != null ?
                new ObjectParameter("nvRutaArchivo", nvRutaArchivo) :
                new ObjectParameter("nvRutaArchivo", typeof(string));
    
            var nvDescripcionParameter = nvDescripcion != null ?
                new ObjectParameter("nvDescripcion", nvDescripcion) :
                new ObjectParameter("nvDescripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spiAgregaImDestinosC", id_DestinoParameter, nvRutaArchivoParameter, nvDescripcionParameter);
        }
    
        public virtual int spiInsertaDestino(string nvDestino)
        {
            var nvDestinoParameter = nvDestino != null ?
                new ObjectParameter("nvDestino", nvDestino) :
                new ObjectParameter("nvDestino", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spiInsertaDestino", nvDestinoParameter);
        }
    
        public virtual int spiInsertaSalida(string nvSalida)
        {
            var nvSalidaParameter = nvSalida != null ?
                new ObjectParameter("nvSalida", nvSalida) :
                new ObjectParameter("nvSalida", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spiInsertaSalida", nvSalidaParameter);
        }
    
        public virtual ObjectResult<spsObtieneDestinosImg_Result> spsObtieneDestinosImg()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spsObtieneDestinosImg_Result>("spsObtieneDestinosImg");
        }
    
        public virtual ObjectResult<spVerificaUsuario_Result> spVerificaUsuario(string nvUsu, string nvCont)
        {
            var nvUsuParameter = nvUsu != null ?
                new ObjectParameter("nvUsu", nvUsu) :
                new ObjectParameter("nvUsu", typeof(string));
    
            var nvContParameter = nvCont != null ?
                new ObjectParameter("nvCont", nvCont) :
                new ObjectParameter("nvCont", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spVerificaUsuario_Result>("spVerificaUsuario", nvUsuParameter, nvContParameter);
        }
    
        public virtual ObjectResult<spsObtieneDestinoDet_Result> spsObtieneDestinoDet(Nullable<int> idViaje)
        {
            var idViajeParameter = idViaje.HasValue ?
                new ObjectParameter("idViaje", idViaje) :
                new ObjectParameter("idViaje", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spsObtieneDestinoDet_Result>("spsObtieneDestinoDet", idViajeParameter);
        }
    
        public virtual ObjectResult<spsObtieneCarrusel_Result> spsObtieneCarrusel(Nullable<int> id_Destino)
        {
            var id_DestinoParameter = id_Destino.HasValue ?
                new ObjectParameter("Id_Destino", id_Destino) :
                new ObjectParameter("Id_Destino", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spsObtieneCarrusel_Result>("spsObtieneCarrusel", id_DestinoParameter);
        }
    }
}
